In [44]:
import seaborn as sns
import pandas as pd
import numpy as np

In [45]:
def calculate_age_at_visit(row):
    date_of_birth = row['Data di nascita']
    date_of_visit = row['Date_of_visit']
    age = date_of_visit.year - date_of_birth.year - ((date_of_visit.month, date_of_visit.day) < (date_of_birth.month, date_of_birth.day))
    return age

def count_relapses(patient_id, date):
    
    relapses = Relapse_number[(Relapse_number['Paziente ID'] == patient_id)
                            & (Relapse_number['relapse'] <= date)]
    
    if len(relapses) < 1:
        return 0
    else:
        return relapses.iloc[-1]['Relapse Count']

In [46]:
path = ".../necessary_data.csv"
Air_data =pd.read_csv(path)
Air_data.head(6)

path = ".../Updated_MS.csv"
FS_data =pd.read_csv(path)

Relapse_number = pd.read_csv(".../relapse.csv")

c:\users\mahin vazifehdan\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [47]:
FS_data['Date_of_visit'] = pd.to_datetime(FS_data['Date_of_visit'], format ='%d/%m/%Y')
FS_data['Date of birth'] = pd.to_datetime(FS_data['Date of birth'], format ='%d/%m/%Y')
Air_data['start_date'] = pd.to_datetime(Air_data['start_date'], format ='%d/%m/%Y')
Air_data['end_date'] = pd.to_datetime(Air_data['end_date'], format ='%d/%m/%Y')
FS_data['Patient_ID']=FS_data['Patient_ID'].astype(object)
Relapse_number['relapse'] = pd.to_datetime(Relapse_number['relapse'])
FS_data['Relapse_number'] = FS_data.apply(lambda row:count_relapses(row['Patient_ID'],
                                                                    row['Date_of_visit']),
                                          axis=1)

In [48]:
FS_Air_data = FS_data.merge(Air_data, left_on='Patient_ID', right_on = "patient_id", how='inner')
Final_data = FS_Air_data[(FS_Air_data['start_date'] <= FS_Air_data['Date_of_visit']) &
            (FS_Air_data['end_date'] >= FS_Air_data['Date_of_visit'])]
Final_data.dropna(inplace = True)

c:\users\mahin vazifehdan\appdata\local\programs\python\python37\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Index(['Patient_ID', 'Date_of_visit', 'Pyramidal', 'Cerebellar',
       'Thronchioencephalic', 'Sensitive', 'Sphincteric', 'Visual', 'Mental',
       'Deambulation', 'EDSS_score_assessed_by_clinician', 'Date of birth',
       'Sex', 'MS in pediatric age', 'Relapse_number', 'patient_id',
       'patient_postcode', 'station_postcode', 'start_date', 'end_date',
       'PM25_mean', 'PM10_mean', 'CO_mean', 'NO2_mean', 'O3_mean', 'SO2_mean',
       'FG_mean', 'HU_mean', 'PP_mean', 'QQ_mean', 'RR_mean', 'TG_mean',
       'TN_mean', 'TX_mean'],
      dtype='object')

In [49]:
Final_data = Final_data[['Patient_ID', 'Date_of_visit','start_date', 'end_date',
                         'Pyramidal', 'Cerebellar','Thronchioencephalic', 'Sensitive',
                         'Sphincteric', 'Visual', 'Mental','Deambulation', 
                         'EDSS_score_assessed_by_clinician', 'Date of birth','Sex',
                         'MS in pediatric age', 'Relapse_number','PM25_mean','PM10_mean',
                         'CO_mean', 'NO2_mean', 'O3_mean', 'SO2_mean','FG_mean', 'HU_mean',
                         'PP_mean', 'QQ_mean', 'RR_mean', 'TG_mean','TN_mean', 'TX_mean' ]]
Final_data.head()

,Patient_ID,Date_of_visit,start_date,end_date,Pyramidal,Cerebellar,Thronchioencephalic,Sensitive,Sphincteric,Visual,...,O3_mean,SO2_mean,FG_mean,HU_mean,PP_mean,QQ_mean,RR_mean,TG_mean,TN_mean,TX_mean
15609,10667,2014-11-27,2014-11-25,2014-12-01,2.0,1.0,0.0,2.0,0.0,0.0,...,11.778053,5.620833,1.965714,90.250002,1013.600011,16.142857,6.485714,10.008571,8.820000,11.711428
16107,10667,2015-06-11,2015-06-09,2015-06-15,2.0,1.0,0.0,2.0,0.0,0.0,...,76.149819,2.159920,2.564286,73.785714,1014.928583,217.142857,2.671429,22.761428,18.035714,28.867143
16604,10667,2015-12-21,2015-12-15,2015-12-21,2.0,1.0,0.0,2.0,0.0,0.0,...,6.920256,4.261685,1.850000,84.157144,1030.557171,44.000000,0.000000,6.164286,2.812857,10.981429
17099,10667,2016-06-13,2016-06-07,2016-06-13,2.0,1.0,0.0,2.0,0.0,0.0,...,76.580388,2.618100,2.298571,68.885715,1011.685726,244.000000,3.328571,21.038571,16.015714,28.218571
17582,10667,2016-09-12,2016-09-06,2016-09-12,2.0,1.0,1.0,2.0,0.0,0.0,...,72.680506,2.451523,2.324286,52.242857,1017.071446,211.857143,0.000000,24.218571,17.690000,32.182857

In [52]:
Final_data.to_csv("FS_Pollutant_Completed.csv", index= False)